export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Projects } from "./Projects";
export { default as Approach } from "./Approach";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as ScrollToTop } from "./ScrollToTop";
